import { Preset } from '@/types';

export const DEFAULT_PALETTE = [
  '#E84530',
  '#E06850',
  '#D87888',
  '#E8A0A0',
  '#F0B8B8',
];

export const presets: Preset[] = [
  {
    name: 'Calm Ambient',
    settings: {
      circleCount: 80,
      minSize: 8,
      maxSize: 120,
      blurMin: 0.3,
      blurMax: 0.9,
      animationSpeed: 0.2,
      noiseScale: 0.002,
      soundSensitivity: 0.2,
      soundSmoothing: 0.97,
      micGain: 0.5,
      imageIntervalMin: 20,
      imageIntervalMax: 40,
      imageFadeDuration: 3,
      imageIntensity: 0.4,
      hueVariation: 10,
      opacityMin: 0.2,
      opacityMax: 0.7,
      depthOfField: 0.7,
    },
  },
  {
    name: 'Breathing',
    settings: {
      circleCount: 150,
      minSize: 4,
      maxSize: 90,
      blurMin: 0.2,
      blurMax: 0.8,
      animationSpeed: 0.4,
      noiseScale: 0.003,
      soundSensitivity: 0.5,
      soundSmoothing: 0.95,
      micGain: 1.0,
      imageIntervalMin: 15,
      imageIntervalMax: 30,
      imageFadeDuration: 2.5,
      imageIntensity: 0.6,
      hueVariation: 15,
      opacityMin: 0.3,
      opacityMax: 0.85,
      depthOfField: 0.5,
    },
  },
  {
    name: 'Active',
    settings: {
      circleCount: 250,
      minSize: 3,
      maxSize: 70,
      blurMin: 0.1,
      blurMax: 0.6,
      animationSpeed: 0.8,
      noiseScale: 0.004,
      soundSensitivity: 1.0,
      soundSmoothing: 0.92,
      micGain: 1.5,
      imageIntervalMin: 10,
      imageIntervalMax: 20,
      imageFadeDuration: 2,
      imageIntensity: 0.8,
      hueVariation: 20,
      opacityMin: 0.4,
      opacityMax: 0.95,
      depthOfField: 0.3,
    },
  },
  {
    name: 'Grid Pulse',
    settings: {
      circleCount: 300,
      minSize: 4,
      maxSize: 50,
      blurMin: 0.05,
      blurMax: 0.4,
      animationSpeed: 0.5,
      noiseScale: 0.003,
      floatGridBlend: 0.9,
      gridColumns: 25,
      soundSensitivity: 0.8,
      soundSmoothing: 0.93,
      micGain: 1.2,
      imageIntervalMin: 12,
      imageIntervalMax: 25,
      imageFadeDuration: 2,
      imageIntensity: 0.7,
      hueVariation: 12,
      opacityMin: 0.5,
      opacityMax: 1.0,
      depthOfField: 0.2,
    },
  },
  {
    name: 'Deep Bokeh',
    settings: {
      circleCount: 60,
      minSize: 15,
      maxSize: 160,
      blurMin: 0.5,
      blurMax: 1.0,
      animationSpeed: 0.15,
      noiseScale: 0.0015,
      soundSensitivity: 0.15,
      soundSmoothing: 0.98,
      micGain: 0.4,
      imageIntervalMin: 25,
      imageIntervalMax: 50,
      imageFadeDuration: 4,
      imageIntensity: 0.3,
      hueVariation: 8,
      opacityMin: 0.15,
      opacityMax: 0.6,
      depthOfField: 0.9,
    },
  },
];
