import { Preset } from '@/types';

export const DEFAULT_PALETTE = [
  '#E84530',
  '#E06850',
  '#D87888',
  '#E8A0A0',
  '#F0B8B8',
];

export const presets: Preset[] = [
  {
    name: 'Calm Drift',
    settings: {
      circleCount: 80,
      minSize: 8,
      maxSize: 120,
      blurMin: 0.3,
      blurMax: 0.9,
      animationSpeed: 0.2,
      noiseScale: 0.4,
      noiseStrength: 0,
      noiseSpeed: 0,
      driftStrength: 20,
      driftSpeed: 0.15,
      waveStrength: 0,
      waveFrequency: 0.3,
      waveSpeed: 0.2,
      soundSensitivity: 0.3,
      soundSmoothing: 0.97,
      soundBurstDecay: 0.95,
      micGain: 0.5,
      imageIntervalMin: 20,
      imageIntervalMax: 40,
      imageFadeDuration: 3,
      imageIntensity: 0.5,
      mediaEnabled: false,
      hueVariation: 10,
      opacityMin: 0.2,
      opacityMax: 0.7,
      depthOfField: 0.7,
    },
  },
  {
    name: 'Breathing',
    settings: {
      circleCount: 150,
      minSize: 4,
      maxSize: 90,
      blurMin: 0.2,
      blurMax: 0.8,
      animationSpeed: 0.4,
      noiseScale: 0.3,
      noiseStrength: 1.0,
      noiseSpeed: 0.3,
      driftStrength: 15,
      driftSpeed: 0.25,
      waveStrength: 0.4,
      waveFrequency: 0.25,
      waveSpeed: 0.4,
      soundSensitivity: 0.6,
      soundSmoothing: 0.94,
      soundBurstDecay: 0.93,
      micGain: 1.0,
      imageIntervalMin: 15,
      imageIntervalMax: 30,
      imageFadeDuration: 2.5,
      imageIntensity: 0.6,
      mediaEnabled: true,
      hueVariation: 15,
      opacityMin: 0.3,
      opacityMax: 0.85,
      depthOfField: 0.5,
    },
  },
  {
    name: 'Active',
    settings: {
      circleCount: 250,
      minSize: 3,
      maxSize: 70,
      blurMin: 0.1,
      blurMax: 0.6,
      animationSpeed: 0.8,
      noiseScale: 0.15,
      noiseStrength: 1.2,
      noiseSpeed: 0.6,
      driftStrength: 30,
      driftSpeed: 0.5,
      waveStrength: 0.6,
      waveFrequency: 0.12,
      waveSpeed: 0.7,
      soundSensitivity: 1.2,
      soundSmoothing: 0.90,
      soundBurstDecay: 0.88,
      micGain: 1.5,
      imageIntervalMin: 10,
      imageIntervalMax: 20,
      imageFadeDuration: 2,
      imageIntensity: 0.8,
      mediaEnabled: true,
      hueVariation: 20,
      opacityMin: 0.4,
      opacityMax: 0.95,
      depthOfField: 0.3,
    },
  },
  {
    name: 'Grid Pulse',
    settings: {
      circleCount: 300,
      minSize: 2,
      maxSize: 30,
      blurMin: 0.0,
      blurMax: 0.2,
      animationSpeed: 0.5,
      noiseScale: 0.2,
      noiseStrength: 0.6,
      noiseSpeed: 0.4,
      driftStrength: 10,
      driftSpeed: 0.3,
      waveStrength: 0.8,
      waveFrequency: 0.15,
      waveSpeed: 0.5,
      floatGridBlend: 1.0,
      gridColumns: 40,
      gridMinSize: 2,
      gridMaxSize: 25,
      soundSensitivity: 1.0,
      soundSmoothing: 0.91,
      soundBurstDecay: 0.90,
      micGain: 1.2,
      imageIntervalMin: 12,
      imageIntervalMax: 25,
      imageFadeDuration: 2,
      imageIntensity: 0.8,
      mediaEnabled: true,
      hueVariation: 12,
      opacityMin: 0.6,
      opacityMax: 1.0,
      depthOfField: 0.1,
    },
  },
  {
    name: 'Deep Bokeh',
    settings: {
      circleCount: 60,
      minSize: 15,
      maxSize: 160,
      blurMin: 0.5,
      blurMax: 1.0,
      animationSpeed: 0.15,
      noiseScale: 0.5,
      noiseStrength: 0,
      noiseSpeed: 0,
      driftStrength: 8,
      driftSpeed: 0.1,
      waveStrength: 0,
      waveFrequency: 0.5,
      waveSpeed: 0.15,
      soundSensitivity: 0.2,
      soundSmoothing: 0.98,
      soundBurstDecay: 0.96,
      micGain: 0.4,
      imageIntervalMin: 25,
      imageIntervalMax: 50,
      imageFadeDuration: 4,
      imageIntensity: 0.4,
      mediaEnabled: false,
      hueVariation: 8,
      opacityMin: 0.15,
      opacityMax: 0.6,
      depthOfField: 0.9,
    },
  },
];
