export const synthSkins = {
  pling: {
    bg: '#d9e4e2',
    primary: '#2c8ca0',
    secondary: '#426c78',
    stripe: '#8fd4e0',
    text: '#142128',
    label: 'PLING',
    sub: 'HIGH SPARKLE OSCILLATOR',
    type: 'C-60',
    displayFont: '"Helvetica Neue", Arial, sans-serif',
    labelFont: '"Courier New", monospace',
  },
  plong: {
    bg: '#ebe2cf',
    primary: '#cc7b2d',
    secondary: '#785331',
    stripe: '#f0c064',
    text: '#24180f',
    label: 'PLONG',
    sub: 'FM MALLET DRIVER',
    type: 'C-90',
    displayFont: '"Helvetica Neue", Arial, sans-serif',
    labelFont: '"Courier New", monospace',
  },
  bong: {
    bg: '#e7dde6',
    primary: '#b0558c',
    secondary: '#70465e',
    stripe: '#d596ba',
    text: '#241720',
    label: 'BONG',
    sub: 'LOW FM RESONANCE',
    type: 'C-120',
    displayFont: '"Helvetica Neue", Arial, sans-serif',
    labelFont: '"Courier New", monospace',
  },
  pad: {
    bg: '#dde4d7',
    primary: '#4f8a63',
    secondary: '#4a6551',
    stripe: '#9dcc85',
    text: '#182118',
    label: 'PAD',
    sub: 'DRONE CHORD BED',
    type: 'E-180',
    displayFont: '"Helvetica Neue", Arial, sans-serif',
    labelFont: '"Courier New", monospace',
  },
  drums: {
    bg: '#e3dbd4',
    primary: '#c45c3e',
    secondary: '#7a4232',
    stripe: '#e89878',
    text: '#1f140f',
    label: 'DRUMS',
    sub: '16-STEP SEQUENCER',
    type: 'DR-16',
    displayFont: '"Helvetica Neue", Arial, sans-serif',
    labelFont: '"Courier New", monospace',
  },
  vr: {
    bg: '#dedbea',
    primary: '#6e72b8',
    secondary: '#52557d',
    stripe: '#a7a9de',
    text: '#191a24',
    label: 'REACT',
    sub: 'VISUAL REACTION BUS',
    type: 'VHS',
    displayFont: '"Helvetica Neue", Arial, sans-serif',
    labelFont: '"Courier New", monospace',
  },
} as const;

export const companionSurfaces = {
  setup: {
    style: 'companion-rack',
    accent: '#d8bf87',
    accentSoft: '#90754f',
    shell: '#111014',
    glass: 'rgba(18, 16, 20, 0.86)',
    displayFont: '"Arial Narrow", "Arial Black", sans-serif',
    labelFont: '"Courier New", monospace',
  },
  live: {
    style: 'companion-remote',
    accent: '#e5d4a6',
    accentSoft: '#907d50',
    shell: '#120f13',
    glass: 'rgba(17, 15, 19, 0.88)',
    displayFont: 'Impact, "Arial Black", sans-serif',
    labelFont: '"Courier New", monospace',
  },
} as const;
